config/routes.rb
Rails.application.routes.draw do

  root 'store#index'
  resources :line_items
  resources :carts
  resources :products

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end


  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  validates_presence_of :name, :price, :description
  validates_uniqueness_of :name
  validates_numericality_of :price, :greater_than_or_equal_to => 1


  def self.latest
    Product.order(:updated_at).last
    # Indexes/shows the product that was updated most recently.
    # controller.perform_caching needs to be => true
  end


  private
    # Ensure that there are no line items referencing this product.
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  respond_to :html

  def index
    @carts = Cart.all
    respond_with(@carts)
  end

  def show
    @carts = set_cart
    respond_with(@cart)
  end

  def new
    @cart = Cart.new
    respond_with(@cart)
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.save

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was updated' }
        format.json { render action: 'show', status: :created,
                            location: @cart, alert: 'Cart has been updated' }
      else
        format.html { render action: 'new', alert: 'Cart was not updated' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @cart.update(cart_params)
    respond_with(@cart)
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice:  'Your cart is now empty' }
      format.json { head :no_content }
    end
  end

  private

    def invalid_cart
      logger.error 'Attempt to access invalid cart #{params[:id]} '
      redirect_to root_url, alert: 'Invalid cart', class: 'bg-danger'
    end

    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private

    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  include CurrentCart

  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @line_items = LineItem.all
    respond_with(@line_items)
  end

  def show
    respond_with(@line_item)
  end

  def new
    @line_item = LineItem.new
    respond_with(@line_item)
  end

  def edit
  end

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to root_url,
                                  notice: 'Item was added to your cart' }
        format.js { @current_item = @line_item }
        format.json { render action: 'show', status: :created,
                             location: @line_item }
      else
        format.html { render action:  'new',
                             alert: 'Something went wrong, item  was not saved.' }
        format.json { render json: @line_item.errors,
                             status: :unprocessable_entity }

      end
    end
  end

  def update
    @line_item.update(line_item_params)
    respond_with(@line_item)
  end

  def destroy
    @line_item.destroy
    respond_with(@line_item.cart)
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def line_item_params
    params.require(:line_item).permit(:product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.order(:name)
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save

    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :image, :description)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  include CurrentCart
  before_action :set_cart

  def index
    @products = Product.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes['style'] = 'display: none'
    else
      puts "Empty cart"
    end
    content_tag('div', attributes, &block)
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<h2>Your cart</h2>
<table class="table table-condensed cart-table" id="cart">
  <thead>
  <tr>
    <th>Bottles</th>
    <th>Brand</th>
    <th>Price</th>
    <th></th>
  </tr>
  </thead>

  <%= render 'line_items/line_item' %>

  <tr class="active">
    <td></td>
    <td></td>
    <td></td>
    <td class="total"><strong>Total: </strong><%= number_to_currency(cart.total_price) %></td>
  </tr>
</table>

app/views/carts/_form.html.erb
<%= form_for(@cart, html: { class: 'form-horizontal', role: 'form' })  do |f| %>
  <% if @cart.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, 'error') %> prohibited this cart from being saved:</h2>

      <ul>
        <% @cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<h1>Your cart</h1>
<%= hidden_div_if(@cart.line_items.empty?, id: 'empty-btn')  do %>
  <p><%= button_to 'Empty your cart', @cart,
                   method: :delete, data: { confirm: 'Are you sure?' },
                   class: 'btn btn-primary', id: 'empty-btn' %></p>
<% end %>

  <%= render @cart %>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/_cart_button.html.erb
<% if @cart %>
  <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
  <div class="cart-btn">
      <!--Cart Button START-->
      <form class="navbar-form navbar-left" role="search">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
          View cart
        </button>
      </form>
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header bg-primary">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Your Cart</h4>
            </div>
            <div class="modal-body">
              <%= render @cart %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <!--<button type="button" class="btn btn-primary">Save changes</button>-->
            </div>
          </div>
        </div>
      </div>
      </div>
      <!--Cart Button END-->
    <% end %>
  <% end %>
<br/><br/>

app/views/layouts/_error_messages.html.erb
<div class="center">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Barsty', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Products', products_path %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
          role="button" aria-expanded="false">Account<span
          class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Profile', '#' %></li>
            <li><%= link_to 'Edit Profile', '#' %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', '#' %></li>
          </ul>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barsty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= render 'layouts/cart_button' %>
    <%= render 'layouts/error_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item, html: { class: 'form-horizontal', role: 'form' })  do |f| %>
  <% if @line_item.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, 'error') %> prohibited this line_item from being saved:</h2>

      <ul>
        <% @line_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% @cart.line_items.each do |item| %>
  <% if item == @current_item %>
    <tr id="current_item">
      <% else %>
  <% end %>
    <tr class="">
      <td><%= item.quantity %><br/><small><em>each: <%= number_to_currency(item.product.price) %></em></small></td>
      <td> <%= item.product.name %><br/><%= image_tag(item.product.image.thumb) %></td>
      <td><%= number_to_currency(item.total_price) %></td>
      <td><%= link_to 'Remove', item, method: :delete, data: { confirm: 'Remove item?' }, class: 'btn btn-sm btn-default' %></td>
    </tr>
<% end %>

app/views/line_items/create.js.erb
$('#cart').html('<%= escape_javascript render(@cart) %>');

$('#current_item').css({'background-color':'#FFCF85'}).
    animate({'background-color':'#B4C978'}, 3000);

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/products/_form.html.erb
<%= form_for(@product, html: { class: 'form-horizontal', role: 'form' })  do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(@product.errors.count, 'error') %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="1"></th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag(product.image.medium) %></td>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm:
                                                                     'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: 'btn btn-default' %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="center jumbotron">
  <p>
    <h3><%= @product.name %></h3>
  </p>

  <p>
    <%= number_to_currency(@product.price) %>
  </p>

  <p>
    <%= image_tag(@product.image.large) %>
  </p>

  <p>
    <%= @product.description %>
  </p>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<h1>Barsty Store</h1>
<h4><em>Bottles for you to choose from</em></h4>

<% cache ['store', Product.latest] do %>
<% @products.each do |product| %>
<% cache ['entry', product] do %>
  <div class="jumbotron">
    <%= image_tag(product.image.large, class: 'img-rounded') %>
    <p><h2><%= product.name %></h2></p>
    <p><%= sanitize(product.description) %></p>
    <p><%= number_to_currency(product.price) %></p>
    <p>
      <%= button_to 'Add to cart', line_items_path(product_id: product), remote: true,
                  class: 'btn btn-primary' %>
    </p>
  </div>
<% end %>
<% end %>
<% end %>

<%= render 'layouts/footer' %>